[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹"
type = "url-test"
rule = ["(é¦™?æ¸¯|HK|Hong Kong)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 60

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹"
type = "url-test"
rule = ["(å°æ¹¾?|æ–°åŒ—|å½°åŒ–|TW|Taiwan)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 60

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹"
type = "url-test"
rule = ["(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|[^-]æ—¥|JP|Japan)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 100

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹"
type = "url-test"
rule = ["(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 100

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹"
type = "url-test"
rule = ["((æ–°åŠ )?å¡|ç‹®åŸ|SG|Singapore)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 100

[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹"
type = "url-test"
rule = ["(ç¾å›½?|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|United States)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 100

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§èŠ‚ç‚¹"
type = "url-test"
rule = ["(åŠ ?æ‹¿å¤§|CA|Canada)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 100
